"""added table with logs

Revision ID: 19ce6bc698ab
Revises: b1d7ba25a633
Create Date: 2025-01-21 18:28:10.820230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19ce6bc698ab"
down_revision: Union[str, None] = "b1d7ba25a633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
