"""Added new table and time add for others tables

Revision ID: 64fa8514216b
Revises: c1488f6f98f2
Create Date: 2025-01-21 00:06:51.914004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64fa8514216b"
down_revision: Union[str, None] = "c1488f6f98f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("authors", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("books", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("books", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "updated_at")
    op.drop_column("books", "created_at")
    op.drop_column("authors", "updated_at")
    op.drop_column("authors", "created_at")
    # ### end Alembic commands ###
