"""Add cascade delete in table Books

Revision ID: c1488f6f98f2
Revises: bf7a5ca12de4
Create Date: 2025-01-19 23:39:36.524858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1488f6f98f2'
down_revision: Union[str, None] = 'bf7a5ca12de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
